config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :update, :edit] do
    resources :articles, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!
  def index
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(body: article_params[:body], user_id: current_user.id)
    redirect_to root_path
  end

  def edit
    @article = Article.find(params[:id])
    unless user_signed_in? && @article.user_id == current_user.id
      redirect_to new_user_session_path
    end
  end

  def update
    article = Article.find(params[:id])
    if user_signed_in? && article.user_id == current_user.id
      article.update(article_params)
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    article = Article.find(params[:id])
    if user_signed_in? && article.user_id == current_user.id
      article.destroy
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end
  private
  def article_params
    params.require(:article).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, only: [:index]
  def index
    @articles = Article.all.order("created_at DESC")
    if user_signed_in?
      gon.current_user_id = current_user.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content white-text">
        <p><%= article.body %></p>
      </div>
      <div class="action-btn">
        <%= link_to '編集', edit_user_article_path(article.user_id, article.id), method: :get, style: "color:white" %>
        <%= link_to '削除', user_article_path(article.user_id, article.id), method: :delete, style: "color:white" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for @article, :url => {:action => :update} do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body %>
      <%= f.submit "編集" %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for @article, :url => {:action => :create} do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body %>
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
  <nav>
    <div class="nav-wrapper grey lighten-1">
      <p class="brand-logo">Dwayne Blog　<span class="subtitle">〜If you smell what The Rock is cookin'!〜</span</p>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
          <% unless user_signed_in? %>
            <%= link_to 'Sign-In', new_user_session_path, method: :get %></li>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to 'Sign-Out', destroy_user_session_path, method: :delete %></li>
          <% end %>
        <li>
          <% if user_signed_in? %>
            <%= link_to '投稿する', new_user_article_path(current_user.id), method: :get %></li>
          <% end %>
      </ul>
    </div>
  </nav>
  <%= image_tag "dwayne1.png", style: "width:100vw", class: "dwayne1"%></div>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<%= image_tag "dwayne2.png", style: "width:100vw", class: "dwayne2"%></div>
<div class="wrapper">
  <% @articles.each do |article| %>
    <%= render partial: "./articles/index", locals: {article: article} %>
  <% end %>
</div>